config/routes.rb
Rails.application.routes.draw do
  resources :favs
  resources :comments
  resources :issues, :path => "contatti" do
      collection do
         get "confirmation"
      end
  end
  resources :cities
  resources :custom_queries
  resources :contacts
  resources :properties
  resources :property_categories
  resources :defaults
  resources :ubiquities
  resources :pictures
  resources :breakpoint_matches

  resources :ads, :path => "annunci" do
      member do
        get "increase"
        get "pictures"
        get "toggle"
        get "pay"
      end
      collection do
        get "admin"
        get "cities"
        get "set_ads_order"
        get "by_zone"
        get "setup"
      end
  end

  resources :ads, :path => "accompagnatrici", only: [:show]



  resources :breakpoints
  resources :ad_categories, :path => "pages" do
      collection do
      get "disclaimer"
      get "infos"
      end
  end
  resources :breakpoint_categories
  devise_for :users

  resources :users do
      member do
        get "show"
        get "guest"
      end
      collection do
        get "properties"
        get "index"
        post "update_user"
        put "up"
        get "profile"
        get "infos"
      end
  end

  root "ads#index"

  scope "/(:category)" do
    scope "/(:city)" do
      resources :ads, only: [:index], :path => "annunci"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :ad_category
  has_many :breakpoint_matches
  has_many :pictures
  has_many :ubiquities
  has_many :comments

  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  after_create :set_title
  accepts_nested_attributes_for :pictures


  extend FriendlyId
  friendly_id :title, use: :slugged

  def amount
    Ad.where({
        :base => self.base,
        :ad_category_id => self.ad_category_id
      }).count
  end


  def set_title
    self.update_attributes({
        :title => self.user.username
      })
  end

  def google_map(center)
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=800x400&zoom=17"
  end

end

app/models/ad_category.rb
class AdCategory < ApplicationRecord
  extend FriendlyId
  has_many :ads
  friendly_id :name, use: :slugged
end

app/models/breakpoint.rb
class Breakpoint < ApplicationRecord
  belongs_to :breakpoint_category
  default_scope { order(:name) } 
end

app/models/city.rb
class City < ApplicationRecord
  default_scope { order('name ASC') }

  def full_name
     name+" ("+prov+")"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ad
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/custom_query.rb
class CustomQuery < ApplicationRecord
end

app/models/default.rb
class Default < ApplicationRecord

  def self.by el
    str = nil
    begin
      str = self.where({:field => el}).first.value.html_safe
    rescue => err
      p err
      str = ""
    end

    str

  end

end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user
  belongs_to :ad
end

app/models/issue.rb
class Issue < ApplicationRecord
  OPTIONS = ["Inserimento annuncio", "Suggerimenti", "Segnalazioni fake", "Reclami", "Pubblicità","Altro"]

end

app/models/picture.rb
require 'paperclip_processors/watermark'
class Picture < ApplicationRecord
  belongs_to :ad
  default_scope { order(order_nr: :asc) }

  has_attached_file :attachment,
                      styles: {
                        :crop => "500x500#",
                        # original: {
                        #   geometry:       "800>",
                        #   auto_orient:    false,
                        #   position: "Center"
                        # },
                        :vertical => "640x1136#"
                      }

  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/


  def cropped
    self.attachment.url(:crop)
  end


end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :property_category
end

app/models/ubiquity.rb
class Ubiquity < ApplicationRecord
  belongs_to :ad
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :breakpoint_matches
  has_many :properties
  has_many :comments
  has_many :contacts
  has_many :ads
  has_many :favs

  PAYMENT_METHODS = ["Contanti", "Assegno", "Bonifico", "Paypal"]

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to confirmation_issues_url, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to confirmation_issues_url, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:name, :email, :city, :motivation, :content)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/defaults_helper.rb
module DefaultsHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issues/_form.html.erb
<%= form_for(issue) do |f| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %>
    <%= f.text_field :name, :placeholder => "Inserisci il tuo nome" %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, :placeholder => "Inserisci la tua email" %>
  </div>

  <div class="field">
    <%= f.label :city, "Città" %> <br/>
    <%= f.collection_select :city, City.all, :name, :full_name, {:class => "form-control"} %> </br>
  </div>

  <div class="field">
    <%= f.label :motivation, "Motivo del contatto" %> <br/>
    <%= f.select(:motivation, Issue::OPTIONS) %>
  </div>

  <div class="field">
    <%= f.label :content, "Messaggio" %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit "INVIA" %>
  </div>
<% end %>

app/views/issues/confirmation.html.erb
<p class="text-center big m20h p20h">
  La tua email è stata inviata correttamente, grazie! <br/>
  <a href="/" class="btn">CLICCA QUI PER CONTINUARE LA NAVIGAZIONE</a>
</p>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>City</th>
      <th>Motivation</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.name %></td>
        <td><%= issue.email %></td>
        <td><%= issue.city %></td>
        <td><%= issue.motivation %></td>
        <td><%= issue.content %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<div class="col-sm-8 white p20h m20h col-sm-offset-2">
<h3 class="text-center">Contatti</h3>

<div class"white">
  <%= render 'form', issue: @issue %>
</div>
</div>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @issue.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @issue.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @issue.city %>
</p>

<p>
  <strong>Motivation:</strong>
  <%= @issue.motivation %>
</p>

<p>
  <strong>Content:</strong>
  <%= @issue.content %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>