config/routes.rb
Rails.application.routes.draw do
  resources :favs
  resources :comments
  resources :issues, :path => "contatti" do
      collection do
         get "confirmation"
      end
  end
  resources :cities
  resources :custom_queries
  resources :contacts
  resources :properties
  resources :property_categories
  resources :defaults
  resources :ubiquities
  resources :pictures
  resources :breakpoint_matches

  resources :ads, :path => "annunci" do
      member do
        get "increase"
        get "pictures"
        get "toggle"
        get "pay"
      end
      collection do
        get "admin"
        get "cities"
        get "set_ads_order"
        get "by_zone"
        get "setup"
      end
  end

  resources :ads, :path => "accompagnatrici", only: [:show]



  resources :breakpoints
  resources :ad_categories, :path => "pages" do
      collection do
      get "disclaimer"
      get "infos"
      end
  end
  resources :breakpoint_categories
  devise_for :users

  resources :users do
      member do
        get "show"
        get "guest"
      end
      collection do
        get "properties"
        get "index"
        post "update_user"
        put "up"
        get "profile"
        get "infos"
      end
  end

  root "ads#index"

  scope "/(:category)" do
    scope "/(:city)" do
      resources :ads, only: [:index], :path => "annunci"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :ad_category
  has_many :breakpoint_matches
  has_many :pictures
  has_many :ubiquities
  has_many :comments

  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  after_create :set_title
  accepts_nested_attributes_for :pictures


  extend FriendlyId
  friendly_id :title, use: :slugged

  def amount
    Ad.where({
        :base => self.base,
        :ad_category_id => self.ad_category_id
      }).count
  end


  def set_title
    self.update_attributes({
        :title => self.user.username
      })
  end

  def google_map(center)
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=800x400&zoom=17"
  end

end

app/models/ad_category.rb
class AdCategory < ApplicationRecord
  extend FriendlyId
  has_many :ads
  friendly_id :name, use: :slugged
end

app/models/breakpoint.rb
class Breakpoint < ApplicationRecord
  belongs_to :breakpoint_category
  default_scope { order(:name) } 
end

app/models/city.rb
class City < ApplicationRecord
  default_scope { order('name ASC') }

  def full_name
     name+" ("+prov+")"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ad
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/custom_query.rb
class CustomQuery < ApplicationRecord
end

app/models/default.rb
class Default < ApplicationRecord

  def self.by el
    str = nil
    begin
      str = self.where({:field => el}).first.value.html_safe
    rescue => err
      p err
      str = ""
    end

    str

  end

end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user
  belongs_to :ad
end

app/models/issue.rb
class Issue < ApplicationRecord
  OPTIONS = ["Inserimento annuncio", "Suggerimenti", "Segnalazioni fake", "Reclami", "Pubblicità","Altro"]

end

app/models/picture.rb
require 'paperclip_processors/watermark'
class Picture < ApplicationRecord
  belongs_to :ad
  default_scope { order(order_nr: :asc) }

  has_attached_file :attachment,
                      styles: {
                        :crop => "500x500#",
                        # original: {
                        #   geometry:       "800>",
                        #   auto_orient:    false,
                        #   position: "Center"
                        # },
                        :vertical => "640x1136#"
                      }

  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/


  def cropped
    self.attachment.url(:crop)
  end


end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :property_category
end

app/models/ubiquity.rb
class Ubiquity < ApplicationRecord
  belongs_to :ad
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :breakpoint_matches
  has_many :properties
  has_many :comments
  has_many :contacts
  has_many :ads
  has_many :favs

  PAYMENT_METHODS = ["Contanti", "Assegno", "Bonifico", "Paypal"]

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to "/"
  end

  def update_user

      p params

  end

  def guest
    @user = current_user
    respond_to do |format|
      format.html
    end

  end


  def show

    @user = User.find(params[:id])

    if @user.user_type == "C"

      redirect_to guest_user_path(@user)

    else

    if current_user.ads.count > 0
      @ad = current_user.ads.last.id
    end

    if current_user.contacts.count > 0
      @contact = current_user.contacts.first
    else
      @contact = Contact.new
    end

    @breakpoint_match = BreakpointMatch.new

    if current_user.user_type == "A"
        redirect_to "/"
    end



    respond_to do |format|
      format.html
    end

  end

  end

  def admin
    @custom_queries = CustomQuery.all
  end


  def properties
    @user = current_user

    if !@user.username
      flash[:notice] = 'Inserisci prima le tue informazioni, quali nome e numero di telefono, grazie!'
      redirect_to @user
    end

    @props = Property.where({
        :user_id => current_user.id
      })


    respond_to do |format|
      format.html
    end
  end

  def profile
    @user = current_user
    @ad = current_user.ads.last.id
    @breakpoint_match = BreakpointMatch.new

    if current_user.properties.count == 0
      redirect_to properties_users_path
    end



    respond_to do |format|
      format.html
      format.json { render :json => current_user.ads.last.breakpoint_matches.to_json() }
    end

  end



  # PATCH/PUT /breakpoints/1
  # PATCH/PUT /breakpoints/1.json
  def update
    begin
      u = params[:id] == current_user.id ? current_user : User.find(params[:id])
    rescue
      u = current_user
    end
    respond_to do |format|
      if u.update(user_params)
        format.html { redirect_to "/", notice: '' }
        format.json { render :json => u.to_json() }
      else
        format.html { render :edit }
        format.json { render json: u.errors, status: :unprocessable_entity }
      end
    end
  end



  def infos
    @user = current_user
    respond_to do |format|
      format.html
    end
  end


  private

      def user_params
        params.require(:user).permit(:user_type, :username, :tel, :deal_from, :deal_to, :payment_method, :deal_notes)
      end

end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/defaults_helper.rb
module DefaultsHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_all.html.erb
<div class="col-sm-12">
<%= search_form_for @qq, url: admin_ads_path do |f| %>
<div class="field col-sm-12">
<%= f.search_field :email_or_username_cont, {:placeholder => "cerca per nome o per email e premi invio", :autocomplete => "off"} %>
</div>
<%= f.submit "CERCA", :class => "hidden" %>
<%end%>
</div>


<%
  @verified = User.where({:user_type => "U"}).where.not({:deal_to => nil})
  @unverified = User.where({:user_type => "U", :deal_to => nil})
%>
<div class="m20h p20h col-sm-12" id="utenti">
<table class="table">
  <thead>
    <th>Utente</th>
    <th>Numero annunci</th>
    <th>Data di registrazione</th>
    <th>Validità abbonamento</th>
    <th>Metodologia di pagamento</th>
    <th>Opzioni</th>
  </thead>

<tbody>
<%@verified.order("username ASC").each do |user|%>
  <tr class="">
    <td><%= user.username%></td>
    <td><%= user.ads.count%></td>
    <td><%= user.created_at.strftime("%d/%m/%Y %H:%M")%></td>
    <td class="minifield">
      <input type="date" value="<%= user.deal_from%>" placeholder="valido dal" data-id="<%= user.id %>" data-controller="users" data-attr="deal_from" onchange="utilities.update(this)"> - <input type="date" value="<%= user.deal_to%>" placeholder="al" data-id="<%= user.id %>" data-controller="users" data-attr="deal_to" onchange="utilities.update(this)"></td>
    <td>
      <select name="payment_method"  data-id="<%= user.id %>" data-controller="users" data-attr="payment_method" onchange="utilities.update(this)">
            <option value="--" <%= 'selected' if user.payment_method == '--' %> >--</option>
            <option value="contanti" <%= 'selected' if user.payment_method == 'contanti' %> >contanti</option>
            <option value="assegno" <%= 'selected' if user.payment_method == 'assegno' %> >assegno</option>
            <option value="bonifico" <%= 'selected' if user.payment_method == 'bonifico' %> >bonifico</option>
            <option value="paypal" <%= 'selected' if user.payment_method == 'paypal' %> >paypal</option>
      </select>
    </td>
    <td>
      <%= link_to 'Elimina', user, method: :delete, data: { confirm: 'Sei sicuro?' } %>
    </td>
  </tr>
<%end%>
<%@unverified.each do |user|%>
  <tr class="unverified">
    <td><%= user.username%></td>
    <td><%= user.ads.count%></td>
    <td><%= user.created_at.strftime("%d/%m/%Y %H:%M")%></td>
    <td class="minifield">
      <input type="date" value="<%= user.deal_from%>" placeholder="valido dal" data-id="<%= user.id %>" data-controller="users" data-attr="deal_from" onchange="utilities.update(this)"> - <input type="date" value="<%= user.deal_to%>" placeholder="al" data-id="<%= user.id %>" data-controller="users" data-attr="deal_to" onchange="utilities.update(this)"></td>
    <td>
      <select name="payment_method"  data-id="<%= user.id %>" data-controller="users" data-attr="payment_method" onchange="utilities.update(this)">
            <option value="--" <%= 'selected' if user.payment_method == '--' %> >--</option>
            <option value="contanti" <%= 'selected' if user.payment_method == 'contanti' %> >contanti</option>
            <option value="assegno" <%= 'selected' if user.payment_method == 'assegno' %> >assegno</option>
            <option value="bonifico" <%= 'selected' if user.payment_method == 'bonifico' %> >bonifico</option>
            <option value="paypal" <%= 'selected' if user.payment_method == 'paypal' %> >paypal</option>
      </select>
    </td>
    <td>
      <%= link_to 'Elimina', user, method: :delete, data: { confirm: 'Sei sicuro?' } %>
    </td>
  </tr>
<%end%>
</tbody>
</table>

</div>


<%content_for :scripts do %>
  <%= javascript_include_tag 'lib/utilities', 'data-turbolinks-track' => true %>
<% end %>

app/views/users/guest.html.erb
<div class="col-sm-10 col-sm-offset-1">
<h3>I tuoi preferiti</h3>
<div class="row">
<%current_user.favs.each do |fav|
    ad = fav.ad
%>
  <div class="col-sm-4 col-xs-12 p5h m10h adpreview">
    <%begin%>
    <a class="p10h m5h" title="<%= ad.user.username%> <%= ad.ad_category.name+" accompagnatrice a "+ad.base%>" href="/accompagnatrici/<%= ad.slug%>">


      <% if ad.pictures.size > 0%>
      <div class="ad bigad col-sm-12 text-white" style="background-image:url('<%= ad.pictures.first.attachment.url(:original)%>')">
      <%else%>
      <div class="ad bigad col-sm-12 text-white no-p">
      <%end%>

      <% if ad.in_tour%>
          <img src="/assets/tour-ico.png" class="tour_ico" alt="">
      <%end%>

      <% if ad.new_photo%>
          <img src="/assets/new-pics.png" class="new_pics" alt="">
      <%end%>
			<div style="position:absolute; padding-top:100%;bottom:0;width:100%;left: 0" class="p10w p10h evdnc">
					<p class=" bold italic text-white text-left no-m no-p p20h"><%= ad.abstract%></p>

			</div>

      </div>


      <div style="position:relative; top:10px;">
        <%begin%>
          <h4 style="color:#EC43A8;"  class="username block no-m"><%= ad.user.username%></h4>
          <small class=" bold italic text-left no-m no-p"><a href="/<%= ad.ad_category.name%>/<%= ad.base%>/annunci"><%= ad.ad_category.name%> a <%= ad.base%></a></small>
          <%rescue%>
          <%end%>
      </div>

    </a>
    <%rescue%>
    <%end%>
  </div>
<%end%>

</div>

<hr>
<div class="col-sm-12">
  <div class="row">
<h3>I tuoi commenti</h3>
<div class="row">
<% @user.comments.each do |comment| %>
  <div class="col-sm-4">
    <input type="number" style="font-size:.5em !important;" class="rating" value="<%= comment.rating.to_i%>" data-readonly />
    <small class="bold secondary_label"><%= link_to comment.ad.title, comment.ad %></small>
    <p class="bold"><%= comment.title %></p>
    <p><%= comment.content.truncate(150) %>...</p>
    <hr>
  </div>
<% end %>
</div>
</div>
</div>
</div>

app/views/users/infos.html.erb
<div class="col-sm-offset-1 col-sm-2 m20h p20h">
  <%= link_to "Inserisci le tue informazioni", infos_users_path, {:class => "bold"}%>
</div>
<div class="col-sm-6">
<div class="col-sm-10 col-sm-offset-1">
<h3>Inserisci le tue informazioni</h3>
<%= form_for(@user, :url => {:action => "update_user"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username, "Scegli un nome" %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :tel, "Inserisci il tuo numero di telefono" %>
    <%= f.text_field :tel, :placeholder => "es: 333 ******1" %>
  </div>

  <div class="actions">
    <%= f.submit "Conferma" %>
  </div>
<% end %>

</div>
</div>

app/views/users/profile.html.erb
<div class="row">
  <div class="col-sm-6 m20h p20h col-sm-offset-3">


    <h3 class="text-center">Inserisci alcune informazioni su di te</h3>



<% BreakpointCategory.all.each do |bc|%>
  <div class="col-xs-12  m20h p20h">
      <h4><%= bc.name %></h4>
     <% bc.breakpoints.each do |bp|%>
     <%if bc.breakpoints.count > 5 %>
      <div class="field bmatch col-xs-4">
          <input type="checkbox" class="bm"  data-aid="<%= @ad %>" data-bp="<%= bp.id%>" data-bc="<%= bc.id%>"><label class="p10w"><%= bp.name%></label>
      </div>
      <%else%>
      <div class="field bmatch">
          <input type="checkbox" class="bm"  data-aid="<%= @ad %>" data-bp="<%= bp.id%>" data-bc="<%= bc.id%>"><label class="p10w"><%= bp.name%></label>
      </div>
      <%end%>
     <%end%>
  </div>
<%end%>
</div>
</div>

<div class="col-xs-6 col-xs-offset-3">
  <%= link_to "Avanti", new_ad_path, :class => "btn btn-system col-xs-12"%>
</div>


<% content_for :scripts do %>
  <script>

      function create(el){
        var data = {
          breakpoint_id: $(el).attr("data-bp"),
          breakpoint_category_id: $(el).attr("data-bc"),
          ad_id: $(el).attr("data-aid")
        };
        utils.post({
            url: "/breakpoint_matches.json",
            data : {
              "breakpoint_match" : data
            },
            callback: function(response){
              $(el).attr({
                "data-id" : response.id
              })
              console.log(response);
            }
        })
      }



      function destroy(el){
        console.log($(el).attr("data-id"))
        utils.delete({
            url: "/breakpoint_matches/"+$(el).attr("data-id")+".json",
            callback: function(){
              $(el).attr({
                "data-id" : null
              })
            }
        })
      }



      $(document).ready(function(){

                $(".bm").on("change",function(el){
                  if($(this).data("id")){
                      destroy($(this));
                  }else{
                     create($(this))
                  }
                })


              utils.get({
                  url : "/users/profile.json",
                  callback: function(r){
                      $.each(r,function(i,e){
                        $("input[data-bc='"+e.breakpoint_category_id+"'][data-bp='"+e.breakpoint_id+"']").attr({
                          "checked": "checked",
                          "data-id" : e.id
                        })
                      })
                  }
              })



      })
  </script>
<% end%>

app/views/users/properties.html.erb
<div class="col-sm-8 col-sm-offset-2 p20h m20h">
  <h3 class="text-center"><%= Default.find_by_field("insert_properties").value%></h3>

<div class="col-sm-12 m20h p20h">
<% PropertyCategory.all.each do |pc|%>
    <div class="col-sm-4 field">
      <label class="bold" for="<%= pc.id%>"><%= pc.name%></label>
      <% _p = @props.find_by_property_category_id(pc.id)
      if _p
      %>
      <input type="text" class="_pc" data-pcid="<%= pc.id%>" name="p_<%= pc.id%>" id="p_<%= pc.id%>" placeholder="<%= pc.placeholder%>" value="<%= _p.value%>" data-id="<%= _p.id%>">
      <%else%>
      <%
         _values = pc.placeholder.split(",")
      %>
      <%if _values.count > 1%>
        <select class="form-control _pc m10h" data-pcid="<%= pc.id%>" name="p_<%= pc.id%>" id="p_<%= pc.id%>"  name="">
          <option value="--">--</option>
            <% _values.each do |v|%>
              <option value="<%= v%>"><%= v%></option>
            <% end%>
        </select>
      <%else%>
      <input type="text" class="_pc" data-pcid="<%= pc.id%>" name="p_<%= pc.id%>" id="p_<%= pc.id%>" placeholder="<%= pc.placeholder%>">
      <%end%>

      <%end%>
    </div>
<%end%>
</div>
</div>

<div class="col-sm-6 col-sm-offset-3">
  <%= link_to "Avanti", new_ad_path, :class => "btn btn-system pull-right"%>
</div>



<% content_for :scripts do %>
<script>

    function createProperty(el){
        var obj = {
          value: $(el).val(),
          property_category_id: $(el).attr("data-pcid"),
          user_id: "<%= current_user.id%>"
        }

        utils.post({
            data: obj,
            url: "/properties.json",
            callback: function(res){
                $(el).attr("data-id", res.id);
            },
            fallback: function(){

            }
        })


    }


        function updateProperty(el){
            var obj = {
              value: $(el).val(),
              property_category_id: $(el).attr("data-pcid"),
              user_id: "<%= current_user.id%>"
            }

            utils.put({
                data: obj,
                url: "/properties/"+$(el).attr("data-id")+".json",
                callback: function(res){
                    $(el).attr("data-id", res.id);
                },
                fallback: function(){

                }
            })


        }

    $(document).ready(function(){
        $(document).on("change","._pc",function(){
            if($(this).attr("data-id")){
              updateProperty($(this));
            }else{
              createProperty($(this));
            }
        })
    })
</script>
<%end%>

app/views/users/show.html.erb
<div class="hidden-xs m20h p20h col-sm-2 col-sm-offset-1">
  <ul class="affix nav nav-pills nav-stacked">
    <li><a href="#annunci" class="">annunci</a></li>
    <li><a href="#infos" class="">informazioni</a></li>
    <li><a href="/users/properties" class="">caratteristiche</a></li>
    <li><a href="#contacts" class="">contatti</a></li>
</ul>
</div>
<div class="col-sm-8 ">

  <div class="m20h p20h col-sm-12" id="annunci">
    <%if @user.ads.count != 0%>
  <h3>I tuoi annunci</h3>
  <table class="table">
    <thead>
      <th>Utente</th>
      <th>Data</th>
      <th>Luogo</th>
      <th>Visualizzazioni</th>
      <th>Opzioni</th>
    </thead>

  <tbody>
  <%@user.ads.each do |ad|%>
    <tr>
      <td><%= ad.created_at.strftime("%d/%m/%Y %H:%M")%></td>
      <td><%= ad.address%></td>
      <td><%= ad.views_count || 0%></td>
      <td>
        <%= link_to "Visualizza", ad%><br/>
        <%= link_to 'Modifica', edit_ad_path(ad) %><br/><%= link_to 'Elimina', ad, method: :delete, data: { confirm: 'Sei sicura?' } %></td>
    </tr>
  <%end%>
  </tbody>
  </table>
  <div class="actions col-sm-3 no-p">
  <%= link_to "Pubblica annuncio", new_ad_path, :class => "btn btn-system col-xs-12 inline-block m20h"%>
  </div>

  <%else%>

      <div class="text-center">
        <h3>I tuoi annunci</h3>
        <p>Inserisci il tuo primo annuncio, segui le istruzioni e carica le tue foto,<br/> per renderti facilmente rintracciabile!</p>

        <div class="actions col-sm-4 col-sm-offset-4 no-p">
        <%= link_to "Inizia ora!", new_ad_path, :class => "btn btn-system col-xs-12 inline-block m20h"%>
        </div>

      </div>


  <%end%>






  </div>
  <hr class="col-sm-12">

  <div class="m20h p20h">
    <p id="notice" class="col-sm-12 text-center bold italic evidence-txt underline"><%= notice %></p>

<%= render "layouts/edit_infos"%>
</div>







<%= render "layouts/contacts"%>

</div>