config/routes.rb
Rails.application.routes.draw do
  resources :favs
  resources :comments
  resources :issues, :path => "contatti" do
      collection do
         get "confirmation"
      end
  end
  resources :cities
  resources :custom_queries
  resources :contacts
  resources :properties
  resources :property_categories
  resources :defaults
  resources :ubiquities
  resources :pictures
  resources :breakpoint_matches

  resources :ads, :path => "annunci" do
      member do
        get "increase"
        get "pictures"
        get "toggle"
        get "pay"
      end
      collection do
        get "admin"
        get "cities"
        get "set_ads_order"
        get "by_zone"
        get "setup"
      end
  end

  resources :ads, :path => "accompagnatrici", only: [:show]



  resources :breakpoints
  resources :ad_categories, :path => "pages" do
      collection do
      get "disclaimer"
      get "infos"
      end
  end
  resources :breakpoint_categories
  devise_for :users

  resources :users do
      member do
        get "show"
        get "guest"
      end
      collection do
        get "properties"
        get "index"
        post "update_user"
        put "up"
        get "profile"
        get "infos"
      end
  end

  root "ads#index"

  scope "/(:category)" do
    scope "/(:city)" do
      resources :ads, only: [:index], :path => "annunci"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :ad_category
  has_many :breakpoint_matches
  has_many :pictures
  has_many :ubiquities
  has_many :comments

  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  after_create :set_title
  accepts_nested_attributes_for :pictures


  extend FriendlyId
  friendly_id :title, use: :slugged

  def amount
    Ad.where({
        :base => self.base,
        :ad_category_id => self.ad_category_id
      }).count
  end


  def set_title
    self.update_attributes({
        :title => self.user.username
      })
  end

  def google_map(center)
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=800x400&zoom=17"
  end

end

app/models/ad_category.rb
class AdCategory < ApplicationRecord
  extend FriendlyId
  has_many :ads
  friendly_id :name, use: :slugged
end

app/models/breakpoint.rb
class Breakpoint < ApplicationRecord
  belongs_to :breakpoint_category
  default_scope { order(:name) } 
end

app/models/city.rb
class City < ApplicationRecord
  default_scope { order('name ASC') }

  def full_name
     name+" ("+prov+")"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ad
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/custom_query.rb
class CustomQuery < ApplicationRecord
end

app/models/default.rb
class Default < ApplicationRecord

  def self.by el
    str = nil
    begin
      str = self.where({:field => el}).first.value.html_safe
    rescue => err
      p err
      str = ""
    end

    str

  end

end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user
  belongs_to :ad
end

app/models/issue.rb
class Issue < ApplicationRecord
  OPTIONS = ["Inserimento annuncio", "Suggerimenti", "Segnalazioni fake", "Reclami", "Pubblicità","Altro"]

end

app/models/picture.rb
require 'paperclip_processors/watermark'
class Picture < ApplicationRecord
  belongs_to :ad
  default_scope { order(order_nr: :asc) }

  has_attached_file :attachment,
                      styles: {
                        :crop => "500x500#",
                        # original: {
                        #   geometry:       "800>",
                        #   auto_orient:    false,
                        #   position: "Center"
                        # },
                        :vertical => "640x1136#"
                      }

  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/


  def cropped
    self.attachment.url(:crop)
  end


end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :property_category
end

app/models/ubiquity.rb
class Ubiquity < ApplicationRecord
  belongs_to :ad
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :breakpoint_matches
  has_many :properties
  has_many :comments
  has_many :contacts
  has_many :ads
  has_many :favs

  PAYMENT_METHODS = ["Contanti", "Assegno", "Bonifico", "Paypal"]

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/new
  def all
    @property_categories = PropertyCategory.all

  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create

    existing_props = Property.where({
        :user_id => property_params[:user_id],
        :property_category_id => property_params[:property_category_id]
      })

    existing_props.each do |ep|
      p ep
      ep.destroy
    end

    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:property_category_id, :user_id, :value)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/properties/_all.html.erb
<div class="m20h p20h col-sm-12" id="props">
  <table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% PropertyCategory.all.each do |property_category| %>
      <tr>
        <td><%= property_category.name %></td>
        <td><%= link_to 'Modifica', edit_property_category_path(property_category) %></td>
        <td><%= link_to 'Elimina', property_category, method: :delete, data: { confirm: 'Sicuro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/properties/_form.html.erb
<%= form_for(property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_category %>
    <%= f.text_field :property_category %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Propery category</th>
      <th>User</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property_category %></td>
        <td><%= property.user %></td>
        <td><%= property.value %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Propery category:</strong>
  <%= @property.property_category %>
</p>

<p>
  <strong>User:</strong>
  <%= @property.user %>
</p>

<p>
  <strong>Value:</strong>
  <%= @property.value %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>