config/routes.rb
Rails.application.routes.draw do
  resources :favs
  resources :comments
  resources :issues, :path => "contatti" do
      collection do
         get "confirmation"
      end
  end
  resources :cities
  resources :custom_queries
  resources :contacts
  resources :properties
  resources :property_categories
  resources :defaults
  resources :ubiquities
  resources :pictures
  resources :breakpoint_matches

  resources :ads, :path => "annunci" do
      member do
        get "increase"
        get "pictures"
        get "toggle"
        get "pay"
      end
      collection do
        get "admin"
        get "cities"
        get "set_ads_order"
        get "by_zone"
        get "setup"
      end
  end

  resources :ads, :path => "accompagnatrici", only: [:show]



  resources :breakpoints
  resources :ad_categories, :path => "pages" do
      collection do
      get "disclaimer"
      get "infos"
      end
  end
  resources :breakpoint_categories
  devise_for :users

  resources :users do
      member do
        get "show"
        get "guest"
      end
      collection do
        get "properties"
        get "index"
        post "update_user"
        put "up"
        get "profile"
        get "infos"
      end
  end

  root "ads#index"

  scope "/(:category)" do
    scope "/(:city)" do
      resources :ads, only: [:index], :path => "annunci"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :ad_category
  has_many :breakpoint_matches
  has_many :pictures
  has_many :ubiquities
  has_many :comments

  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  after_create :set_title
  accepts_nested_attributes_for :pictures


  extend FriendlyId
  friendly_id :title, use: :slugged

  def amount
    Ad.where({
        :base => self.base,
        :ad_category_id => self.ad_category_id
      }).count
  end


  def set_title
    self.update_attributes({
        :title => self.user.username
      })
  end

  def google_map(center)
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=800x400&zoom=17"
  end

end

app/models/ad_category.rb
class AdCategory < ApplicationRecord
  extend FriendlyId
  has_many :ads
  friendly_id :name, use: :slugged
end

app/models/breakpoint.rb
class Breakpoint < ApplicationRecord
  belongs_to :breakpoint_category
  default_scope { order(:name) } 
end

app/models/city.rb
class City < ApplicationRecord
  default_scope { order('name ASC') }

  def full_name
     name+" ("+prov+")"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ad
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/custom_query.rb
class CustomQuery < ApplicationRecord
end

app/models/default.rb
class Default < ApplicationRecord

  def self.by el
    str = nil
    begin
      str = self.where({:field => el}).first.value.html_safe
    rescue => err
      p err
      str = ""
    end

    str

  end

end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user
  belongs_to :ad
end

app/models/issue.rb
class Issue < ApplicationRecord
  OPTIONS = ["Inserimento annuncio", "Suggerimenti", "Segnalazioni fake", "Reclami", "Pubblicità","Altro"]

end

app/models/picture.rb
require 'paperclip_processors/watermark'
class Picture < ApplicationRecord
  belongs_to :ad
  default_scope { order(order_nr: :asc) }

  has_attached_file :attachment,
                      styles: {
                        :crop => "500x500#",
                        # original: {
                        #   geometry:       "800>",
                        #   auto_orient:    false,
                        #   position: "Center"
                        # },
                        :vertical => "640x1136#"
                      }

  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/


  def cropped
    self.attachment.url(:crop)
  end


end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  belongs_to :property_category
end

app/models/ubiquity.rb
class Ubiquity < ApplicationRecord
  belongs_to :ad
  geocoded_by :address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :breakpoint_matches
  has_many :properties
  has_many :comments
  has_many :contacts
  has_many :ads
  has_many :favs

  PAYMENT_METHODS = ["Contanti", "Assegno", "Bonifico", "Paypal"]

end

app/controllers/custom_queries_controller.rb
class CustomQueriesController < ApplicationController
  before_action :set_custom_query, only: [:show, :edit, :update, :destroy]

  # GET /custom_queries
  # GET /custom_queries.json
  def index
    @custom_queries = CustomQuery.all
  end

  # GET /custom_queries
  # GET /custom_queries.json
  def all
    @custom_queries = CustomQuery.all
  end

  # GET /custom_queries/1
  # GET /custom_queries/1.json
  def show
  end

  # GET /custom_queries/new
  def new
    @custom_query = CustomQuery.new
  end

  # GET /custom_queries/1/edit
  def edit
  end

  # POST /custom_queries
  # POST /custom_queries.json
  def create
    @custom_query = CustomQuery.new(custom_query_params)

    respond_to do |format|
      if @custom_query.save
        format.html { redirect_to "/", notice: 'Custom query was successfully created.' }
        format.json { render :show, status: :created, location: @custom_query }
      else
        format.html { render :new }
        format.json { render json: @custom_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_queries/1
  # PATCH/PUT /custom_queries/1.json
  def update
    respond_to do |format|
      if @custom_query.update(custom_query_params)
        format.html { redirect_to "/", notice: 'Custom query was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_query }
      else
        format.html { render :edit }
        format.json { render json: @custom_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_queries/1
  # DELETE /custom_queries/1.json
  def destroy
    @custom_query.destroy
    respond_to do |format|
      format.html { redirect_to custom_queries_url, notice: 'Custom query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_query
      @custom_query = CustomQuery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_query_params
      params.require(:custom_query).permit(:title, :path, :query, :order)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/custom_queries_helper.rb
module CustomQueriesHelper
end

app/helpers/favs_helper.rb
module FavsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/custom_queries/_all.html.erb
<div class="m20h p20h col-sm-12" id="queries">

<div class="row text-right">
  <%= link_to 'Nuovo link', new_custom_query_path, :class => "btn btn-system" %>

</div>


<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Url</th>
      <th>Query</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% CustomQuery.all.each do |custom_query| %>
      <tr>
        <td><%= custom_query.title %></td>
        <td><%= custom_query.path %></td>
        <td><%= custom_query.query %></td>
        <td><%= custom_query.order %></td>
        <td><%= link_to 'Show', custom_query %></td>
        <td><%= link_to 'Edit', edit_custom_query_path(custom_query) %></td>
        <td><%= link_to 'Destroy', custom_query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/custom_queries/_form.html.erb
<%= form_for(custom_query) do |f| %>
  <% if custom_query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(custom_query.errors.count, "error") %> prohibited this custom_query from being saved:</h2>

      <ul>
      <% custom_query.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :query %>
    <%= f.text_field :query %>
  </div>
  <div class="field">
    <%= f.label :order %>
    <%= f.text_field :order %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/custom_queries/edit.html.erb
<div class="m20h"></div>
<div class="m20h"></div>
<div class="m20h"></div>
<div class="col-sm-8 white p20h m20h col-sm-offset-2">
<h3 class="text-center">Modifica link</h3>

<div class"white">
  <%= render 'form', custom_query: @custom_query %>
</div>
</div>

app/views/custom_queries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Custom Queries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_queries.each do |custom_query| %>
      <tr>
        <td><%= custom_query.title %></td>
        <td><%= custom_query.path %></td>
        <td><%= link_to 'Show', custom_query %></td>
        <td><%= link_to 'Edit', edit_custom_query_path(custom_query) %></td>
        <td><%= link_to 'Destroy', custom_query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom Query', new_custom_query_path %>

app/views/custom_queries/new.html.erb
<div class="m20h"></div>
<div class="m20h"></div>
<div class="m20h"></div>
<div class="col-sm-8 white p20h m20h col-sm-offset-2">
<h3 class="text-center">Aggiungi link</h3>

<div class"white">
  <%= render 'form', custom_query: @custom_query %>
</div>
</div>

app/views/custom_queries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @custom_query.title %>
</p>

<p>
  <strong>Path:</strong>
  <%= @custom_query.path %>
</p>

<%= link_to 'Edit', edit_custom_query_path(@custom_query) %> |
<%= link_to 'Back', custom_queries_path %>